<a href="https://colab.research.google.com/github/Japjotongithub/Pattern-Printing/blob/main/NUMPY%2CPANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
myarr=np.array([3,5,6,7])
print(myarr)
print(myarr[0])


[3 5 6 7]
3


# Array Creation
Array Creation

In [ ]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)
print(listarray.dtype)
print(listarray.shape)
print(listarray.size)

[[1 2 3]
 [5 8 5]
 [0 3 1]]
int64
(3, 3)
9


In [ ]:
zeros=np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
rng=np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
lspace=np.linspace(1,50,10)
print(lspace)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [ ]:
x=[[1,2 ,3],[2, 3, 4],[3, 4, 5]]
ar=np.array(x)
ar.sum(axis=1)
print(ar.T)
print(ar.argmax())                #returns index of largest element in array
print(ar.argsort())               #returns indices that sort each row

[[1 2 3]
 [2 3 4]
 [3 4 5]]
8
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
y=[[1,2,4],[2,3,3],[3,4,7]]
ar2=np.array(y)
ar*ar2                #multiplies a11 with b11,a12 with b12.......

array([[ 1,  4, 12],
       [ 4,  9, 12],
       [ 9, 16, 35]])

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
#Matrix multiplication
result1 = np.dot(A, B)
print(result1)

[[19 22]
 [43 50]]


# Pandas


In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.rand(334,5))
df.drop(33,axis=0)
df.head(2)

0         1         2         3         4
0  0.684397  0.760986  0.910133  0.093920  0.438770
1  0.619431  0.871177  0.907741  0.920566  0.318698

In [ ]:
df.index

RangeIndex(start=0, stop=334, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.T

0         1         2         3         4         5         6    \
0  0.816422  0.456687  0.034198  0.963520  0.352573  0.688763  0.921619   
1  0.535666  0.706127  0.752538  0.678697  0.966025  0.205794  0.824771   
2  0.990715  0.792241  0.896521  0.743005  0.723179  0.335091  0.969035   
3  0.363305  0.172202  0.720645  0.065578  0.409949  0.622571  0.522044   
4  0.951135  0.530965  0.478949  0.577660  0.475836  0.465382  0.506837   

        7         8         9    ...       324       325       326       327  \
0  0.082477  0.481241  0.814680  ...  0.816169  0.995816  0.444883  0.494850   
1  0.257286  0.512518  0.337036  ...  0.229276  0.399452  0.172728  0.198470   
2  0.984106  0.665113  0.992573  ...  0.358980  0.168475  0.533819  0.713463   
3  0.952226  0.224312  0.788538  ...  0.976472  0.516446  0.277934  0.545579   
4  0.217067  0.733192  0.710730  ...  0.645239  0.616902  0.350942  0.085434   

        328       329       330       331       332       333  
0  0.849414  0.944826  0.072702  0.912668  0.737612  0.172252  
1  0.917288  0.144987  0.744718  0.982248  0.365935  0.462363  
2  0.051822  0.787537  0.259904  0.223247  0.474083  0.810488  
3  0.544363  0.419190  0.241548  0.848404  0.177276  0.453065  
4  0.836881  0.699545  0.719957  0.569055  0.802116  0.443174  

[5 rows x 334 columns]

In [ ]:
df.loc[[1,3],:]

0         1         2         3         4
1  0.619431  0.871177  0.907741  0.920566  0.318698
3  0.102063  0.903973  0.742836  0.233698  0.406709

In [ ]:
print(df.loc[(df[3]<0.4)& (df[2]>0.3)])

            0         1         2         3         4
0    0.684397  0.760986  0.910133  0.093920  0.438770
3    0.102063  0.903973  0.742836  0.233698  0.406709
4    0.605828  0.533709  0.645450  0.106523  0.674085
15   0.494443  0.217572  0.639216  0.241677  0.915824
16   0.498020  0.686281  0.368998  0.045387  0.544123
..        ...       ...       ...       ...       ...
302  0.770006  0.449480  0.458508  0.099267  0.111810
312  0.109683  0.023252  0.940963  0.278635  0.285768
322  0.974974  0.032269  0.320239  0.025978  0.240999
331  0.969704  0.159501  0.986785  0.273460  0.518328
332  0.808208  0.525573  0.583007  0.240753  0.519384

[81 rows x 5 columns]


In [ ]:
df.drop([3],axis=1)                                #drops 3rd column

0         1         2         4
0    0.684397  0.760986  0.910133  0.438770
1    0.619431  0.871177  0.907741  0.318698
2    0.511905  0.651140  0.035185  0.144160
3    0.102063  0.903973  0.742836  0.406709
4    0.605828  0.533709  0.645450  0.674085
..        ...       ...       ...       ...
329  0.613331  0.725302  0.897211  0.226373
330  0.526784  0.003563  0.710859  0.998534
331  0.969704  0.159501  0.986785  0.518328
332  0.808208  0.525573  0.583007  0.519384
333  0.703001  0.212602  0.513306  0.330496

[334 rows x 4 columns]